[global]
type=global
user_agent=SIP-App-DevContainer

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
allow_reload=yes

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0:8088
allow_reload=yes

[1001]
type=endpoint
context=phones
disallow=all
allow=ulaw,alaw
auth=1001
aors=1001
transport=transport-ws
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
dtmf_mode=rfc4733

[1001]
type=auth
auth_type=userpass
username=1001
password=1234

[1001]
type=aor
max_contacts=1
remove_existing=yes

[1002]
type=endpoint
context=phones
disallow=all
allow=ulaw,alaw
auth=1002
aors=1002
transport=transport-ws
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
dtmf_mode=rfc4733

[1002]
type=auth
auth_type=userpass
username=1002
password=1234

[1002]
type=aor
max_contacts=1
remove_existing=yes
